name: new-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest 
    steps:
      - name: "Minha primeira acao"
        run: echo "Hello world"
      - name: "Segunda acao"
        run: 
          echo "Voce criou seu primeiro workflow"
          echo "Parabens"
          
